OpenCaption/Models/Script.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Text;

namespace OpenCaption.Models
{
    public class Script : ScriptManager
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string FileName { get; set; }
        public int WorkId { get; set; }
        public Work Work { get; set; }
        public int VenueId { get; set; }
        public Venue Venue { get; set; }
        public virtual ICollection<Text> Texts { get; set; }
        public virtual ICollection<Element> Elements { get; set; }
        public int CharacterCount { get; set; }
        public bool Original { get; set; }
        [DisplayName("Language/Version")]
        public string Language { get; set; }
        public DateTime CreatedDate { get; set; }

        public void GenerateTextScript()
        {
            GenerateTextScript(Id, FileName);
        }


        /// <summary>
        /// Used for Parsing a new file into the database for the Uploads specified work
        /// </summary>
        /// <param name="file"></param>
        public void ParseNewScript()
        {
            // Get database context
            using (CaptionDataContext data = new CaptionDataContext())
            {
                // Speed up upload
                data.Configuration.AutoDetectChangesEnabled = false;

                // Get refrence to the work the script will be loaded for
                Work work = data.Work.First(w => w.Id == WorkId);
                this.Work = work;
                
                // Remove old texts and elements
                CleanTextsAndElements();

                CharacterCount = CharacterCount;
                CreatedDate = DateTime.Now;
                // Mark as updated to save character count
                data.Entry(this).State = System.Data.Entity.EntityState.Added;
                
                // Add elements for operator to use
                Element BLANK = data.Element.Add(new Element(){ Script = this, Name = String.Empty, Type = "BLANKLINE" }); // Represented as ##
                Element AUDIENCEMESSAGE = data.Element.Add(new Element(){ Script = this, Name = String.Empty, Type = "AUDIENCEMESSAGE" }); // ##: Message here
                data.SaveChanges();

                // Detects the encoding of the uploaded file
                Encoding encoding = Util.EncodingDetector.GetFileEncoding(FileName);

                // Read the file line by line into array
                string[] lines = File.ReadAllLines(FileName, encoding);

                GenerateLines(this, lines, data);
            }
        }

        


        /// <summary>
        /// Removes any items from the database that were loaded for this script.
        /// Use this before uploading a new script for this play.
        /// Sets character count to zero.
        /// Removes any texts related to this script.
        /// Deletes any Elements created for previous scripts
        /// </summary>
        public void CleanTextsAndElements()
        {
            using (CaptionDataContext data = new CaptionDataContext())
            {
                CleanTexts(data);
                CleanElements(data);
            }
        }

        // Calls database directly to delete all elements for this script
        public void CleanTexts(CaptionDataContext data)
        {
            data.Database.ExecuteSqlCommand(string.Format("DELETE FROM Texts WHERE ScriptId = {0}", Id));
        }

        // Calls database directly to delete all texts
        public void CleanElements(CaptionDataContext data)
        {
            data.Database.ExecuteSqlCommand(string.Format("DELETE FROM Elements WHERE ScriptId = {0}", Id));
        }


        public bool HasTexts()
        {
            return CountTexts() > 0 ? true : false;
        }

        public int CountTexts()
        {
            using (CaptionDataContext db = new CaptionDataContext())
            {
                return db.Text.Count(t => t.Script.Id == Id);
            } 
        }

        public Encoding GetScriptEncoding()
        {
            return GetScriptEncoding(FileName);
        }

        public void RegenerateScriptWithCharacterCount(int? newCount)
        {
            base.RegenerateScriptWithCharacterCount(this, newCount);
        }
    }
}

OpenCaption/Controllers/ScriptController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Threading.Tasks;
using System;
using PagedList;

namespace OpenCaption.Models
{
    public class ScriptController : Controller
    {
        private CaptionDataContext db = new CaptionDataContext();

        // GET: Script
        public ActionResult Index()
        {
            return View(db.Script.ToList());
        }

        // GET: Script/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Script.Find(id);
            if (script == null)
            {
                return HttpNotFound();
            }
            return View(script);
        }

        // GET: Script/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Works/Edit/5
        [Route("Script/{ScriptId}/EditText")]
        public ActionResult EditText(int? ScriptId, int? page)
        {
            int pageSize = 100;
            int pageNumber = (page ?? 1);
            if (ScriptId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Text> text = db.Text.Where(t => t.ScriptId == ScriptId).Include(t => t.Script.Work).ToList();
            if (text == null)
            {
                return HttpNotFound();
            }
            return View(text.ToPagedList(pageNumber, pageSize));
        }

        // POST: Script/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FileName,WorkId,VenueId,CharacterCount,Original,Language,CreatedDate")] Script script)
        {
            if (ModelState.IsValid)
            {
                db.Script.Add(script);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(script);
        }

        // GET: Script/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Script.Find(id);
            ViewData["NewCount"] = new SelectList(Enumerable.Range(25, 25), 33) as IEnumerable<SelectListItem>;
            if (script == null)
            {
                return HttpNotFound();
            }
            return View(script);
        }

        [Route("Script/{workId}/AdjustCharacterCount/{id}")]
        public ActionResult AdjustCharacterCount(int? id, int? workId)
        {
            if (id == null || workId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Script.Where(s => s.Id == id).Include(s => s.Work).First();
            ViewData["NewCount"] = new SelectList(Enumerable.Range(20, 81)) as IEnumerable<SelectListItem>;
            if (script == null)
            {
                return HttpNotFound();
            }
            return View(script);
        }

        // POST: Script/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FileName,WorkId,VenueId,CharacterCount,Original,Language,CreatedDate")] Script script)
        {
            if (ModelState.IsValid)
            {
                db.Entry(script).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(script);
        }

        // GET: Script/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Script.Find(id);
            if (script == null)
            {
                return HttpNotFound();
            }
            return View(script);
        }

        // POST: Script/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Script script = db.Script.Find(id);
            db.Script.Remove(script);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Script/AdjustCount/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdjustCount(int? id, int? newCount)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Script.Find(id);           
            Task.Factory.StartNew(() => AdjustCharacterCountForScript(script, newCount));
            return RedirectToAction("Index", "Admin");
        }

        [Route("Script/{workId}/ExportScript")]
        public ActionResult ExportScript(bool? upload, int workId)
        {
            ViewData["Upload"] = upload == true ? "true" : "false";
            List<Script> scripts = db.Script.Where(s => s.WorkId == workId).Include(s => s.Work).ToList();
            var title = scripts.FirstOrDefault();
            if (title != null)
            {
                ViewData["name"] = title.Work.Name;
            }
            return View(scripts);
        }

        [Route("Script/{workId}/ExportScript/{scriptId}")]
        public ActionResult ExportScript(int scriptId)
        {
            // Start the parsing process in the background
            Task.Factory.StartNew(() => StartExport(scriptId));

            return RedirectToAction("Index", new { upload = true });
        }

        /// <summary>
        /// Thread to export a script for the user to download and edit.
        /// </summary>
        /// <param name="scriptId"></param>
        private void StartExport(int scriptId)
        {
            var alert = new ScriptAlertHub();
            try
            {
                var watch = System.Diagnostics.Stopwatch.StartNew();
                ScriptManager.GenerateTextScript(scriptId, HttpContext.Server.MapPath("~/App_Data/").ToString());
                watch.Stop();
                alert.AlertSuccess("Export of script " + scriptId + " finished in " + watch.ElapsedMilliseconds.ToString() + "ms");
            }
            catch (Exception ex)
            {
                alert.AlertFail("Export to file failed with message" + ex.Message);
            }

        }

        private void AdjustCharacterCountForScript(Script script, int? newCount)
        {
            var alert = new ScriptAlertHub();
            try
            {
                var watch = System.Diagnostics.Stopwatch.StartNew();
                script.RegenerateScriptWithCharacterCount(newCount);
                watch.Stop();
                alert.AlertSuccess("Export of script " + script.Id + " finished in " + watch.ElapsedMilliseconds.ToString() + "ms");
            }
            catch(Exception ex)
            {
                alert.AlertFail("Adjust Character Count failed with message" + ex.Message);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OpenCaption/Views/Script/AdjustCharacterCount.cshtml
@model OpenCaption.Models.Script
@{
    ViewBag.Title = "Edit";
}

<div class="jumbotron minitron">
    <h2>Set Character Count for: @Model.Work.Name @Model.Language</h2>
</div>
<div class="dropdown-wrapper">
    @using (Html.BeginForm("AdjustCount", "Script", FormMethod.Post, new { enctype = "multipart/form-data", id = "adjustCharacterCount" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.HiddenFor(model => model.Id)
            <div class="dropdown-inline">
                @Html.Label("Currently Set: ") 
                @Html.TextBoxFor(model => Model.CharacterCount, new { @readonly = "readonly", @class = "form-control"})
            </div>
            <div class="dropdown-inline">
                @Html.Label("NEW Character Count")
                @Html.DropDownList("NewCount", (IEnumerable<SelectListItem>)ViewData["NewCount"], "Unlimited", new { @class = "form-control" })
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Start Process" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

OpenCaption/Views/Script/Create.cshtml
@model OpenCaption.Models.Script
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Script</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VenueId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VenueId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VenueId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Original, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Original)
                    @Html.ValidationMessageFor(model => model.Original, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OpenCaption/Views/Script/Delete.cshtml
@model OpenCaption.Models.Script

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Script</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Original)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Original)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OpenCaption/Views/Script/Details.cshtml
@model OpenCaption.Models.Script

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Script</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Original)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Original)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OpenCaption/Views/Script/Edit.cshtml
@model OpenCaption.Models.Script

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Script</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
       
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VenueId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VenueId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VenueId, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="dropdown-inline">
                @Html.Label("Character Count")
                @Html.DropDownList("CharacterCount", (IEnumerable<SelectListItem>)ViewData["CharacterCount"], null, new { @class = "form-control" })
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Original, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Original)
                    @Html.ValidationMessageFor(model => model.Original, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OpenCaption/Views/Script/EditText.cshtml
@model PagedList.IPagedList<OpenCaption.Models.Text>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Edit Lines";
}
<div class="jumbotron minitron">
    <h2>Edit Lines: @Html.DisplayFor(model => model.First().Script.Work.Name) @Html.DisplayFor(model => model.First().Script.Language)</h2>
</div>

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("EditText", new { page }))

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Sequence)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Element.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().ContentText)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Visible)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().OperatorNote)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sequence)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Element.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContentText)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Visible)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OperatorNote)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { WorkId = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("EditText", new { page }))

OpenCaption/Views/Script/ExportScript.cshtml
@model IEnumerable<OpenCaption.Models.Script>
@{
    ViewBag.Title = "Productions";
}
<div class="jumbotron minitron">
    <h2>@ViewData["name"] Export and Options</h2>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CharacterCount)
        </th>
        <th>
            Total Lines
        </th>
        <th colspan="2">EDIT</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Language)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CharacterCount)
            </td>
            <td>
                @item.Texts.Count
            </td>
            <td>
                <ul style="list-style: none; padding-left: initial;">
                    <li>
                        <a id="download-original" data-id="@item.Id" href="#">Download Original Script</a> 
                    </li>
                    <li>
                        <a id="generate-text" data-id="@item.Id" href="/Script/@(item.WorkId)/ExportScript/@(item.Id)" >Generate Text for Editing and Re-loading</a>
                    </li>
                    <li>
                        <a href="/Script/@(item.WorkId)/AdjustCharacterCount/@(item.Id)">Consolidate and Adjust Character Count</a>
                    </li>
                </ul>
            </td>
        </tr>
    }
</table>
<script>

    window.onload = function () {

        // Show the message that the upload has started
        if (@(ViewData["Upload"]) == true) {
            simple.client.started("Your Export Has Started");
        }

        // Download Original Function
        $('#download-original').on('click', function(){
            alert("download-original: " + $(this).data("id"));
        });
    }
</script>

OpenCaption/Views/Script/Index.cshtml
@model IEnumerable<OpenCaption.Models.Script>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VenueId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CharacterCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Original)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VenueId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CharacterCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Original)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>